export enum AppTypes {
  INCREMENT = '[APP] INCREMENT',
  DECREMENT = '[APP] DECREMENT',
  RESET = '[APP] RESET',
  GET_DATA = '[APP] GET_DATA',
  GET_DATA_SUCCESS = '[APP] GET_DATA_SUCCESS',
  GET_DATA_FAIL = '[APP] GET_DATA_FAIL',
  GET_FAKE_DATA = '[APP] GET_FAKE_DATA',
  GET_FAKE_DATA_SUCCESS = '[APP] GET_FAKE_DATA_SUCCESS',
}
